/* eslint-disable */
// GENERATED FILE. Do not edit by hand.
// Source: website src/styles/{base,themes,typography}.css via mobile/scripts/generate-design-tokens.mjs.
// Regenerate with `npm run tokens:generate`; `npm run tokens:check` fails on drift.

export const DESIGN_TOKEN_SOURCE_HASHES = {
  "base.css": "dbba35a86ca98567b60431124a932c8a259a28f3b91549cae6221345a96a4d11",
  "themes.css": "715e673fdec4272c3879e178b0994b0e70fab32f02cd65c362c272c634606eeb",
  "typography.css": "779deb0be91cd02093c8bba1617798e508f4cf44ddb792cfba072ed83a030eda"
} as const

export const COLOR_THEME_IDS = ["default","sunset-blaze","forest-emerald","sandalwood","ocean-deep","sakura-blossom","dracula-midnight","lavender-mist","cyberpunk-neon"] as const

export type ColorThemeId = (typeof COLOR_THEME_IDS)[number]
export type DesignTokenName = 'accent' | 'accent-dark' | 'accent-light' | 'bg' | 'blue-bg' | 'body-scale' | 'button-danger-bg' | 'button-danger-border' | 'button-danger-hover' | 'button-danger-ink' | 'button-danger-shadow' | 'button-primary-bg' | 'button-primary-border' | 'button-primary-hover' | 'button-primary-ink' | 'button-primary-shadow' | 'chart-grid' | 'fab-bg' | 'fab-border' | 'fab-ink' | 'focus-accent' | 'focus-bg-a' | 'focus-bg-b' | 'focus-bg-c' | 'focus-caption' | 'focus-control-bg' | 'focus-control-border' | 'focus-control-ink' | 'focus-control-muted' | 'focus-faint' | 'focus-ink' | 'focus-line' | 'focus-muted' | 'focus-orbit' | 'focus-panel' | 'focus-panel-line' | 'focus-selected-bg' | 'focus-selected-border' | 'focus-selected-ink' | 'focus-soft' | 'focus-star' | 'font-body' | 'font-default-reading' | 'font-heading' | 'font-identity' | 'font-label' | 'font-number' | 'font-public' | 'font-ui' | 'green' | 'green-bg' | 'heat-border' | 'heat-goal' | 'heat-high' | 'heat-low' | 'heat-medium' | 'heat-none' | 'ink' | 'ink-soft' | 'line' | 'line-strong' | 'muted' | 'orange' | 'orange-bg' | 'paper' | 'paper-muted' | 'paper-soft' | 'radius' | 'reading-font-family' | 'red' | 'red-bg' | 'ring-track' | 'safe-bottom' | 'score-okay-bg' | 'score-okay-fg' | 'score-strong-bg' | 'score-strong-fg' | 'score-weak-bg' | 'score-weak-fg' | 'shadow' | 'shadow-float' | 'shell-x' | 'sidebar-w' | 'sidebar-x' | 'subject-chemistry' | 'subject-chemistry-bg' | 'subject-maths' | 'subject-maths-bg' | 'subject-physics' | 'subject-physics-bg' | 'surface-cool' | 'surface-cool-accent' | 'surface-cool-accent-bg' | 'surface-cool-border' | 'surface-cool-ink' | 'surface-cool-muted' | 'surface-tip' | 'surface-tip-accent' | 'surface-tip-accent-bg' | 'surface-tip-border' | 'surface-tip-ink' | 'surface-tip-muted' | 'surface-warm' | 'surface-warm-border' | 'surface-warm-ink' | 'surface-warm-line' | 'surface-warm-muted' | 'surface-warm-strong' | 'text-accent' | 'text-muted' | 'text-primary' | 'tint-cool' | 'tint-green-border' | 'tint-green-ink' | 'tint-green-surface' | 'tint-tip' | 'tint-warm' | 'type-alert-size' | 'type-badge-size' | 'type-body-size' | 'type-brand-size' | 'type-button-size' | 'type-caption-size' | 'type-display-size' | 'type-empty-size' | 'type-h1-size' | 'type-h2-size' | 'type-h3-size' | 'type-input-size' | 'type-metric-size' | 'type-nav-size' | 'type-overline-size' | 'type-table-size' | 'yellow-bg'
export type DesignTokenMap = Readonly<Record<DesignTokenName, string>>

/** Token tables keyed by display mode, then by colour theme (`default` is the base palette). */
export const DESIGN_TOKENS: Readonly<Record<'light' | 'dark', Readonly<Record<ColorThemeId, DesignTokenMap>>>> = {
  light: {
    'default': {
      'accent': "#526c9a",
      'accent-dark': "#415982",
      'accent-light': "#e8edf5",
      'bg': "#f7f4ec",
      'blue-bg': "#e8eef7",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#526d9c",
      'button-primary-border': "#475f8b",
      'button-primary-hover': "#465f8e",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#3e5379",
      'chart-grid': "#dbd3bf",
      'fab-bg': "#526c9a",
      'fab-border': "#415982",
      'fab-ink': "#ffffff",
      'focus-accent': "#dfc47e",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f7f4ec",
      'focus-caption': "#4d6451",
      'focus-control-bg': "#fcfaf3",
      'focus-control-border': "#d5cdbb",
      'focus-control-ink': "#29332d",
      'focus-control-muted': "#6b6c62",
      'focus-faint': "#626c5d",
      'focus-ink': "#29332d",
      'focus-line': "#b1b59f",
      'focus-muted': "#506253",
      'focus-orbit': "#adb39d",
      'focus-panel': "#f3f4ec",
      'focus-panel-line': "#adb39d",
      'focus-selected-bg': "#dce3d7",
      'focus-selected-border': "#7a9275",
      'focus-selected-ink': "#334f3a",
      'focus-soft': "#566057",
      'focus-star': "#9f864c",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#3d6a47",
      'green-bg': "#e6f0e6",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#29332d",
      'ink-soft': "#566057",
      'line': "#e8e2d4",
      'line-strong': "#d5cdbb",
      'muted': "#6b6c62",
      'orange': "#8f5620",
      'orange-bg': "#f8eddd",
      'paper': "#fffdf7",
      'paper-muted': "#f1eee4",
      'paper-soft': "#fcfaf3",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a03f38",
      'red-bg': "#f8e9e5",
      'ring-track': "#d8d1bd",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f8eddd",
      'score-okay-fg': "#734517",
      'score-strong-bg': "#e6f0e6",
      'score-strong-fg': "#2e5636",
      'score-weak-bg': "#f8e9e5",
      'score-weak-fg': "#81302a",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#40694e",
      'subject-chemistry-bg': "#e9f1e8",
      'subject-maths': "#8f5620",
      'subject-maths-bg': "#f7eddf",
      'subject-physics': "#3f639b",
      'subject-physics-bg': "#e8eef7",
      'surface-cool': "#eff1f1",
      'surface-cool-accent': "#537198",
      'surface-cool-accent-bg': "#e5e9ed",
      'surface-cool-border': "#c1c6cb",
      'surface-cool-ink': "#3e5772",
      'surface-cool-muted': "#546979",
      'surface-tip': "#f7f1e4",
      'surface-tip-accent': "#95824e",
      'surface-tip-accent-bg': "#f0e8d4",
      'surface-tip-border': "#d7c8a8",
      'surface-tip-ink': "#685f3a",
      'surface-tip-muted': "#797352",
      'surface-warm': "#f7f0e0",
      'surface-warm-border': "#dccaa4",
      'surface-warm-ink': "#706239",
      'surface-warm-line': "#d0be98",
      'surface-warm-muted': "#7b7451",
      'surface-warm-strong': "#836f3b",
      'text-accent': "#415982",
      'text-muted': "#5f655c",
      'text-primary': "#29332d",
      'tint-cool': "#5278b1",
      'tint-green-border': "#b8c0ad",
      'tint-green-ink': "#47664d",
      'tint-green-surface': "#f1f3eb",
      'tint-tip': "#b3924a",
      'tint-warm': "#c49a46",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#fbf2ce",
    },
    'sunset-blaze': {
      'accent': "#b0512a",
      'accent-dark': "#99431f",
      'accent-light': "#f8e4d8",
      'bg': "#f9f2ec",
      'blue-bg': "#f0e4ea",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#99431f",
      'button-primary-border': "#7a3619",
      'button-primary-hover': "#82391a",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#6b2f16",
      'chart-grid': "#e5d2c4",
      'fab-bg': "#b0512a",
      'fab-border': "#99431f",
      'fab-ink': "#ffffff",
      'focus-accent': "#e0955a",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f9f2ec",
      'focus-caption': "#565843",
      'focus-control-bg': "#fcf6f0",
      'focus-control-border': "#d8c0b1",
      'focus-control-ink': "#372a26",
      'focus-control-muted': "#715d55",
      'focus-faint': "#6a6151",
      'focus-ink': "#372a26",
      'focus-line': "#b7ad97",
      'focus-muted': "#585343",
      'focus-orbit': "#b4ab94",
      'focus-panel': "#f4f2ea",
      'focus-panel-line': "#b4ab94",
      'focus-selected-bg': "#dfe1d5",
      'focus-selected-border': "#85906f",
      'focus-selected-ink': "#424d35",
      'focus-soft': "#5c4a43",
      'focus-star': "#9f5b3d",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#4d7043",
      'green-bg': "#e5efdc",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#372a26",
      'ink-soft': "#5c4a43",
      'line': "#ecdcd1",
      'line-strong': "#d8c0b1",
      'muted': "#715d55",
      'orange': "#9a5a1e",
      'orange-bg': "#f8ead4",
      'paper': "#fffaf5",
      'paper-muted': "#f4eae1",
      'paper-soft': "#fcf6f0",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a83a32",
      'red-bg': "#f8e1dd",
      'ring-track': "#e2cbb9",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f8ead4",
      'score-okay-fg': "#7a4816",
      'score-strong-bg': "#e5efdc",
      'score-strong-fg': "#395a33",
      'score-weak-bg': "#f8e1dd",
      'score-weak-fg': "#872d26",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#5d6b2a",
      'subject-chemistry-bg': "#eef0da",
      'subject-maths': "#94500f",
      'subject-maths-bg': "#f8e7d2",
      'subject-physics': "#9c4460",
      'subject-physics-bg': "#f7e1e8",
      'surface-cool': "#f6eae8",
      'surface-cool-accent': "#8d4a5a",
      'surface-cool-accent-bg': "#f1e0df",
      'surface-cool-border': "#d8b6b4",
      'surface-cool-ink': "#6e3b46",
      'surface-cool-muted': "#764a4f",
      'surface-tip': "#f8eee0",
      'surface-tip-accent': "#a0763d",
      'surface-tip-accent-bg': "#f2e4d0",
      'surface-tip-border': "#dec2a1",
      'surface-tip-ink': "#76562f",
      'surface-tip-muted': "#826240",
      'surface-warm': "#f7e7dd",
      'surface-warm-border': "#deb39e",
      'surface-warm-ink': "#77452f",
      'surface-warm-line': "#d1a48d",
      'surface-warm-muted': "#7f5340",
      'surface-warm-strong': "#884c32",
      'text-accent': "#99431f",
      'text-muted': "#6b564d",
      'text-primary': "#372a26",
      'tint-cool': "#a04a63",
      'tint-green-border': "#bfbea9",
      'tint-green-ink': "#536243",
      'tint-green-surface': "#f3f0e9",
      'tint-tip': "#c08a3a",
      'tint-warm': "#c2643a",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f9ecc9",
    },
    'forest-emerald': {
      'accent': "#2e6b4f",
      'accent-dark': "#235a41",
      'accent-light': "#dfeee5",
      'bg': "#f1f6f0",
      'blue-bg': "#e2ebf4",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#235a41",
      'button-primary-border': "#1c4834",
      'button-primary-hover': "#1e4d37",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#193f2e",
      'chart-grid': "#d5e2d0",
      'fab-bg': "#2e6b4f",
      'fab-border': "#235a41",
      'fab-ink': "#ffffff",
      'focus-accent': "#9ec27a",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f1f6f0",
      'focus-caption': "#3d5f4d",
      'focus-control-bg': "#f6faf4",
      'focus-control-border': "#bfd3bd",
      'focus-control-ink': "#24322a",
      'focus-control-muted': "#5c6b5f",
      'focus-faint': "#536b5c",
      'focus-ink': "#24322a",
      'focus-line': "#9cbaa3",
      'focus-muted': "#405d4c",
      'focus-orbit': "#99b8a0",
      'focus-panel': "#eff4ef",
      'focus-panel-line': "#99b8a0",
      'focus-selected-bg': "#d6e3da",
      'focus-selected-border': "#68957b",
      'focus-selected-ink': "#294f3d",
      'focus-soft': "#46584b",
      'focus-star': "#92794a",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#2e6b4f",
      'green-bg': "#e0efe5",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#24322a",
      'ink-soft': "#46584b",
      'line': "#dbe7d8",
      'line-strong': "#bfd3bd",
      'muted': "#5c6b5f",
      'orange': "#8f5a1f",
      'orange-bg': "#f5ead8",
      'paper': "#fbfdf9",
      'paper-muted': "#eaf1e7",
      'paper-soft': "#f6faf4",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a13d35",
      'red-bg': "#f6e2de",
      'ring-track': "#d2dfcc",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f5ead8",
      'score-okay-fg': "#734817",
      'score-strong-bg': "#e0efe5",
      'score-strong-fg': "#23563b",
      'score-weak-bg': "#f6e2de",
      'score-weak-fg': "#822f28",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#2e6b4f",
      'subject-chemistry-bg': "#e0efe5",
      'subject-maths': "#8f5a1f",
      'subject-maths-bg': "#f5ead8",
      'subject-physics': "#33628a",
      'subject-physics-bg': "#e2ebf4",
      'surface-cool': "#e9f0ea",
      'surface-cool-accent': "#35664e",
      'surface-cool-accent-bg': "#dce7e0",
      'surface-cool-border': "#aec7b4",
      'surface-cool-ink': "#29503d",
      'surface-cool-muted': "#3d5f4d",
      'surface-tip': "#eff2e6",
      'surface-tip-accent': "#74854a",
      'surface-tip-accent-bg': "#e4e9d6",
      'surface-tip-border': "#c1ceab",
      'surface-tip-ink': "#536239",
      'surface-tip-muted': "#60714b",
      'surface-warm': "#f2eee2",
      'surface-warm-border': "#cfc7a8",
      'surface-warm-ink': "#695a39",
      'surface-warm-line': "#bdbd9a",
      'surface-warm-muted': "#6d694b",
      'surface-warm-strong': "#7a653d",
      'text-accent': "#235a41",
      'text-muted': "#55645a",
      'text-primary': "#24322a",
      'tint-cool': "#2e6b4f",
      'tint-green-border': "#abc4b2",
      'tint-green-ink': "#37644d",
      'tint-green-surface': "#edf3ed",
      'tint-tip': "#8a9a4a",
      'tint-warm': "#b98a4a",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f2f0d5",
    },
    'sandalwood': {
      'accent': "#7a5a33",
      'accent-dark': "#644926",
      'accent-light': "#efe5cf",
      'bg': "#f6f1e8",
      'blue-bg': "#e5edf3",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#644926",
      'button-primary-border': "#503a1e",
      'button-primary-hover': "#553e20",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#46331b",
      'chart-grid': "#e0d5bd",
      'fab-bg': "#7a5a33",
      'fab-border': "#644926",
      'fab-ink': "#ffffff",
      'focus-accent': "#c9a35f",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f6f1e8",
      'focus-caption': "#51583e",
      'focus-control-bg': "#fbf7ee",
      'focus-control-border': "#d0c1a4",
      'focus-control-ink': "#322a20",
      'focus-control-muted': "#6b5f4c",
      'focus-faint': "#65634b",
      'focus-ink': "#322a20",
      'focus-line': "#b0ae8e",
      'focus-muted': "#52533c",
      'focus-orbit': "#aeac8c",
      'focus-panel': "#f4f4eb",
      'focus-panel-line': "#aeac8c",
      'focus-selected-bg': "#dfe3d6",
      'focus-selected-border': "#81916c",
      'focus-selected-ink': "#3f4e34",
      'focus-soft': "#544938",
      'focus-star': "#8c6b43",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#4c7147",
      'green-bg': "#e4efdf",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#322a20",
      'ink-soft': "#544938",
      'line': "#e5dbc6",
      'line-strong': "#d0c1a4",
      'muted': "#6b5f4c",
      'orange': "#8f5a26",
      'orange-bg': "#f6e8d6",
      'paper': "#fffcf5",
      'paper-muted': "#f1ead9",
      'paper-soft': "#fbf7ee",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#9d4238",
      'red-bg': "#f6e3de",
      'ring-track': "#ddd2b8",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f6e8d6",
      'score-okay-fg': "#73481b",
      'score-strong-bg': "#e4efdf",
      'score-strong-fg': "#385a36",
      'score-weak-bg': "#f6e3de",
      'score-weak-fg': "#7f322a",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#516c3a",
      'subject-chemistry-bg': "#e9f0dd",
      'subject-maths': "#96562a",
      'subject-maths-bg': "#f6e8d6",
      'subject-physics': "#4f6d86",
      'subject-physics-bg': "#e5edf3",
      'surface-cool': "#f0f0eb",
      'surface-cool-accent': "#5a6c70",
      'surface-cool-accent-bg': "#e7e9e4",
      'surface-cool-border': "#c2c2b5",
      'surface-cool-ink': "#485455",
      'surface-cool-muted': "#575c56",
      'surface-tip': "#f2eee0",
      'surface-tip-accent': "#796a39",
      'surface-tip-accent-bg': "#e8e2d0",
      'surface-tip-border': "#c8bc99",
      'surface-tip-ink': "#5a4f2c",
      'surface-tip-muted': "#695c39",
      'surface-warm': "#f4ebdf",
      'surface-warm-border': "#d1bb9b",
      'surface-warm-ink': "#695032",
      'surface-warm-line': "#c4ac88",
      'surface-warm-muted': "#715a3d",
      'surface-warm-strong': "#775a37",
      'text-accent': "#644926",
      'text-muted': "#655947",
      'text-primary': "#322a20",
      'tint-cool': "#5d7a86",
      'tint-green-border': "#babda2",
      'tint-green-ink': "#4f6241",
      'tint-green-surface': "#f2f2e9",
      'tint-tip': "#8a7a3a",
      'tint-warm': "#a97c48",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f4edcd",
    },
    'ocean-deep': {
      'accent': "#1f5f8b",
      'accent-dark': "#164d73",
      'accent-light': "#deebf4",
      'bg': "#edf3f6",
      'blue-bg': "#dfebf4",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#164d73",
      'button-primary-border': "#123e5c",
      'button-primary-hover': "#134162",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#0f3651",
      'chart-grid': "#d2e0e8",
      'fab-bg': "#1f5f8b",
      'fab-border': "#164d73",
      'fab-ink': "#ffffff",
      'focus-accent': "#6fb5c9",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#edf3f6",
      'focus-caption': "#395f5c",
      'focus-control-bg': "#f5f9fb",
      'focus-control-border': "#b7cbd8",
      'focus-control-ink': "#1c2b36",
      'focus-control-muted': "#556773",
      'focus-faint': "#4d696d",
      'focus-ink': "#1c2b36",
      'focus-line': "#96b6b9",
      'focus-muted': "#3b5a5e",
      'focus-orbit': "#94b4b6",
      'focus-panel': "#eff5f4",
      'focus-panel-line': "#94b4b6",
      'focus-selected-bg': "#d6e4e0",
      'focus-selected-border': "#659689",
      'focus-selected-ink': "#264f46",
      'focus-soft': "#3f5261",
      'focus-star': "#907752",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#2f7355",
      'green-bg': "#dfeee7",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#1c2b36",
      'ink-soft': "#3f5261",
      'line': "#d6e2ea",
      'line-strong': "#b7cbd8",
      'muted': "#556773",
      'orange': "#8f5a20",
      'orange-bg': "#f5ead8",
      'paper': "#fbfdfe",
      'paper-muted': "#e7eff4",
      'paper-soft': "#f5f9fb",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a13d3d",
      'red-bg': "#f6e2e2",
      'ring-track': "#cfdde5",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f5ead8",
      'score-okay-fg': "#734817",
      'score-strong-bg': "#dfeee7",
      'score-strong-fg': "#245c40",
      'score-weak-bg': "#f6e2e2",
      'score-weak-fg': "#822f2d",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#1c675e",
      'subject-chemistry-bg': "#ddefec",
      'subject-maths': "#8f5a1f",
      'subject-maths-bg': "#f5ead8",
      'subject-physics': "#1f5f8b",
      'subject-physics-bg': "#dfebf4",
      'surface-cool': "#e7eff4",
      'surface-cool-accent': "#285b7f",
      'surface-cool-accent-bg': "#dae5ed",
      'surface-cool-border': "#a6c0d1",
      'surface-cool-ink': "#1e4662",
      'surface-cool-muted': "#335771",
      'surface-tip': "#e3eeee",
      'surface-tip-accent': "#2b6a68",
      'surface-tip-accent-bg': "#d0e2e1",
      'surface-tip-border': "#9cbfc2",
      'surface-tip-ink': "#1f4e4f",
      'surface-tip-muted': "#346065",
      'surface-warm': "#f2eee7",
      'surface-warm-border': "#ccc4b4",
      'surface-warm-ink': "#64573f",
      'surface-warm-line': "#b8b8ad",
      'surface-warm-muted': "#686559",
      'surface-warm-strong': "#776242",
      'text-accent': "#164d73",
      'text-muted': "#4f6270",
      'text-primary': "#1c2b36",
      'tint-cool': "#1f5f8b",
      'tint-green-border': "#a7c3c0",
      'tint-green-ink': "#35665a",
      'tint-green-surface': "#edf3f2",
      'tint-tip': "#22766c",
      'tint-warm': "#b98a4a",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f0efd4",
    },
    'sakura-blossom': {
      'accent': "#b0446e",
      'accent-dark': "#97365c",
      'accent-light': "#f8e0ea",
      'bg': "#f9f1f3",
      'blue-bg': "#e9e2f2",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#97365c",
      'button-primary-border': "#792b4a",
      'button-primary-hover': "#802e4e",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#6a2640",
      'chart-grid': "#ead4dc",
      'fab-bg': "#b0446e",
      'fab-border': "#97365c",
      'fab-ink': "#ffffff",
      'focus-accent': "#d98aa6",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f9f1f3",
      'focus-caption': "#55524d",
      'focus-control-bg': "#fcf5f8",
      'focus-control-border': "#dcbccb",
      'focus-control-ink': "#3b2731",
      'focus-control-muted': "#745664",
      'focus-faint': "#6b5a5e",
      'focus-ink': "#3b2731",
      'focus-line': "#b8a8ab",
      'focus-muted': "#584d4e",
      'focus-orbit': "#b5a6a9",
      'focus-panel': "#f4f1f1",
      'focus-panel-line': "#b5a6a9",
      'focus-selected-bg': "#dee0db",
      'focus-selected-border': "#828a7c",
      'focus-selected-ink': "#41483c",
      'focus-soft': "#5e4450",
      'focus-star': "#a57281",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#466847",
      'green-bg': "#e3eede",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#3b2731",
      'ink-soft': "#5e4450",
      'line': "#efd9e1",
      'line-strong': "#dcbccb",
      'muted': "#745664",
      'orange': "#96522b",
      'orange-bg': "#f7e8d8",
      'paper': "#fffafc",
      'paper-muted': "#f6e9ee",
      'paper-soft': "#fcf5f8",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a83a4a",
      'red-bg': "#f8dfe3",
      'ring-track': "#e7d0d9",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f7e8d8",
      'score-okay-fg': "#77431e",
      'score-strong-bg': "#e3eede",
      'score-strong-fg': "#345436",
      'score-weak-bg': "#f8dfe3",
      'score-weak-fg': "#872d36",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#596b43",
      'subject-chemistry-bg': "#eaefdf",
      'subject-maths': "#8f4f22",
      'subject-maths-bg': "#f7e8d8",
      'subject-physics': "#7a4a86",
      'subject-physics-bg': "#efe2f2",
      'surface-cool': "#f3eaf1",
      'surface-cool-accent': "#724877",
      'surface-cool-accent-bg': "#ebe0ea",
      'surface-cool-border': "#d1b4c9",
      'surface-cool-ink': "#5c395d",
      'surface-cool-muted': "#694665",
      'surface-tip': "#f7eaef",
      'surface-tip-accent': "#9c5e75",
      'surface-tip-accent-bg': "#f1dde4",
      'surface-tip-border': "#deb5c4",
      'surface-tip-ink': "#754658",
      'surface-tip-muted': "#815265",
      'surface-warm': "#f8ebef",
      'surface-warm-border': "#e2bec9",
      'surface-warm-ink': "#7c5561",
      'surface-warm-line': "#d6adbc",
      'surface-warm-muted': "#825c69",
      'surface-warm-strong': "#8d606e",
      'text-accent': "#97365c",
      'text-muted': "#6c505e",
      'text-primary': "#3b2731",
      'tint-cool': "#7a4a86",
      'tint-green-border': "#c0b9b6",
      'tint-green-ink': "#4f5a4a",
      'tint-green-surface': "#f2f0ef",
      'tint-tip': "#b96a86",
      'tint-warm': "#c98a9a",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f8edda",
    },
    'dracula-midnight': {
      'accent': "#6a3fc0",
      'accent-dark': "#5a31a8",
      'accent-light': "#eae2fb",
      'bg': "#f3f1f9",
      'blue-bg': "#e4e2f6",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#5a31a8",
      'button-primary-border': "#482786",
      'button-primary-hover': "#4d2a8f",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#3f2276",
      'chart-grid': "#dcd7ec",
      'fab-bg': "#6a3fc0",
      'fab-border': "#5a31a8",
      'fab-ink': "#ffffff",
      'focus-accent': "#bd93f9",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f3f1f9",
      'focus-caption': "#395559",
      'focus-control-bg': "#f8f6fd",
      'focus-control-border': "#c6c0df",
      'focus-control-ink': "#2b2640",
      'focus-control-muted': "#5f5a78",
      'focus-faint': "#515e6f",
      'focus-ink': "#2b2640",
      'focus-line': "#9dadbb",
      'focus-muted': "#3f4f5c",
      'focus-orbit': "#9aabb9",
      'focus-panel': "#eff3f4",
      'focus-panel-line': "#9aabb9",
      'focus-selected-bg': "#d4e2df",
      'focus-selected-border': "#5f9086",
      'focus-selected-ink': "#234b46",
      'focus-soft': "#4b4562",
      'focus-star': "#9e8360",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#1b704b",
      'green-bg': "#def0e6",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#2b2640",
      'ink-soft': "#4b4562",
      'line': "#dfdbef",
      'line-strong': "#c6c0df",
      'muted': "#5f5a78",
      'orange': "#935210",
      'orange-bg': "#f6e8d4",
      'paper': "#fcfbff",
      'paper-muted': "#edeaf6",
      'paper-soft': "#f8f6fd",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#b03a3a",
      'red-bg': "#f7e0e0",
      'ring-track': "#d9d3ea",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f6e8d4",
      'score-okay-fg': "#75430d",
      'score-strong-bg': "#def0e6",
      'score-strong-fg': "#175a39",
      'score-weak-bg': "#f7e0e0",
      'score-weak-fg': "#8c2d2b",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#1b704b",
      'subject-chemistry-bg': "#def0e6",
      'subject-maths': "#935210",
      'subject-maths-bg': "#f6e8d4",
      'subject-physics': "#1f6f9e",
      'subject-physics-bg': "#dfeef6",
      'surface-cool': "#eeeff7",
      'surface-cool-accent': "#5c6592",
      'surface-cool-accent-bg': "#e5e6f1",
      'surface-cool-border': "#bfc0dc",
      'surface-cool-ink': "#484e74",
      'surface-cool-muted': "#54567b",
      'surface-tip': "#f5effb",
      'surface-tip-accent': "#9674b3",
      'surface-tip-accent-bg': "#efe4f7",
      'surface-tip-border': "#d3c1e8",
      'surface-tip-ink': "#6c5486",
      'surface-tip-muted': "#755f8f",
      'surface-warm': "#f5f0ea",
      'surface-warm-border': "#d8c8be",
      'surface-warm-ink': "#74604e",
      'surface-warm-line': "#c7b7b9",
      'surface-warm-muted': "#766561",
      'surface-warm-strong': "#876e52",
      'text-accent': "#5a31a8",
      'text-muted': "#585273",
      'text-primary': "#2b2640",
      'tint-cool': "#6272a4",
      'tint-green-border': "#a8bdc1",
      'tint-green-ink': "#2d6054",
      'tint-green-surface': "#ecf1f2",
      'tint-tip': "#b98ad9",
      'tint-warm': "#c9a35f",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f2efd8",
    },
    'lavender-mist': {
      'accent': "#6250a8",
      'accent-dark': "#514190",
      'accent-light': "#e9e5f7",
      'bg': "#f4f3f9",
      'blue-bg': "#e4e8f6",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#514190",
      'button-primary-border': "#413473",
      'button-primary-hover': "#45377a",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#392e65",
      'chart-grid': "#ddd9ec",
      'fab-bg': "#6250a8",
      'fab-border': "#514190",
      'fab-ink': "#ffffff",
      'focus-accent': "#a596d9",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f4f3f9",
      'focus-caption': "#4b595a",
      'focus-control-bg': "#f9f8fd",
      'focus-control-border': "#c9c4de",
      'focus-control-ink': "#2c2a3a",
      'focus-control-muted': "#625f76",
      'focus-faint': "#5d636e",
      'focus-ink': "#2c2a3a",
      'focus-line': "#aab0bc",
      'focus-muted': "#4c535c",
      'focus-orbit': "#a7aeb9",
      'focus-panel': "#f2f4f4",
      'focus-panel-line': "#a7aeb9",
      'focus-selected-bg': "#dce3df",
      'focus-selected-border': "#7b9288",
      'focus-selected-ink': "#3a4e45",
      'focus-soft': "#4d4a60",
      'focus-star': "#947fa5",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#47714f",
      'green-bg': "#e2efe4",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#2c2a3a",
      'ink-soft': "#4d4a60",
      'line': "#e2dff0",
      'line-strong': "#c9c4de",
      'muted': "#625f76",
      'orange': "#8f5a26",
      'orange-bg': "#f5ead8",
      'paper': "#fdfcff",
      'paper-muted': "#efecf6",
      'paper-soft': "#f9f8fd",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#a03d47",
      'red-bg': "#f6e1e4",
      'ring-track': "#dad5e9",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f5ead8",
      'score-okay-fg': "#73481b",
      'score-strong-bg': "#e2efe4",
      'score-strong-fg': "#345a3b",
      'score-weak-bg': "#f6e1e4",
      'score-weak-fg': "#812f34",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#446b52",
      'subject-chemistry-bg': "#e2efe6",
      'subject-maths': "#8f5a26",
      'subject-maths-bg': "#f5ead8",
      'subject-physics': "#4a5aa0",
      'subject-physics-bg': "#e4e8f6",
      'surface-cool': "#efedf7",
      'surface-cool-accent': "#5c4e94",
      'surface-cool-accent-bg': "#e6e2f2",
      'surface-cool-border': "#c1badd",
      'surface-cool-ink': "#483e73",
      'surface-cool-muted': "#554c7b",
      'surface-tip': "#f2effa",
      'surface-tip-accent': "#8173ac",
      'surface-tip-accent-bg': "#e9e4f6",
      'surface-tip-border': "#cbc3e6",
      'surface-tip-ink': "#5f547f",
      'surface-tip-muted': "#6a618b",
      'surface-warm': "#f4eff8",
      'surface-warm-border': "#d4c8e3",
      'surface-warm-ink': "#6d5e7c",
      'surface-warm-line': "#c4b7d8",
      'surface-warm-muted': "#726584",
      'surface-warm-strong': "#7e6b8d",
      'text-accent': "#514190",
      'text-muted': "#5a576e",
      'text-primary': "#2c2a3a",
      'tint-cool': "#6250a8",
      'tint-green-border': "#b7c0c3",
      'tint-green-ink': "#496255",
      'tint-green-surface': "#f0f2f3",
      'tint-tip': "#9a86d0",
      'tint-warm': "#b99ac9",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f2efd8",
    },
    'cyberpunk-neon': {
      'accent': "#0f6f8f",
      'accent-dark': "#0b5a76",
      'accent-light': "#ddf0f6",
      'bg': "#f1f4f8",
      'blue-bg': "#dceef4",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#0b5a76",
      'button-primary-border': "#09485e",
      'button-primary-hover': "#094d64",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#083f53",
      'chart-grid': "#d4dce8",
      'fab-bg': "#0f6f8f",
      'fab-border': "#0b5a76",
      'fab-ink': "#ffffff",
      'focus-accent': "#22d3ee",
      'focus-bg-a': "#eef4e9",
      'focus-bg-b': "#e6efe0",
      'focus-bg-c': "#f1f4f8",
      'focus-caption': "#2f5150",
      'focus-control-bg': "#f6f8fc",
      'focus-control-border': "#b8c2d6",
      'focus-control-ink': "#171c2b",
      'focus-control-muted': "#545c72",
      'focus-faint': "#495f69",
      'focus-ink': "#171c2b",
      'focus-line': "#93adb3",
      'focus-muted': "#334b53",
      'focus-orbit': "#90acb0",
      'focus-panel': "#eef3f4",
      'focus-panel-line': "#90acb0",
      'focus-selected-bg': "#d3e2de",
      'focus-selected-border': "#5b8e7f",
      'focus-selected-ink': "#1a4438",
      'focus-soft': "#3a4157",
      'focus-star': "#987144",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#1d6c45",
      'green-bg': "#dfeee5",
      'heat-border': "rgba(90, 100, 85, 0.13)",
      'heat-goal': "#bd9b53",
      'heat-high': "#608966",
      'heat-low': "#c6d7c3",
      'heat-medium': "#94b498",
      'heat-none': "#efeee7",
      'ink': "#171c2b",
      'ink-soft': "#3a4157",
      'line': "#d8deea",
      'line-strong': "#b8c2d6",
      'muted': "#545c72",
      'orange': "#93511f",
      'orange-bg': "#f6e8d4",
      'paper': "#fbfcff",
      'paper-muted': "#e9edf4",
      'paper-soft': "#f6f8fc",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#b03434",
      'red-bg': "#f7e0e0",
      'ring-track': "#d1d9e6",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#f6e8d4",
      'score-okay-fg': "#754217",
      'score-strong-bg': "#dfeee5",
      'score-strong-fg': "#185735",
      'score-weak-bg': "#f7e0e0",
      'score-weak-fg': "#8c2927",
      'shadow': "0 11px 26px rgba(73, 63, 43, .055), 0 2px 5px rgba(73, 63, 43, .04)",
      'shadow-float': "0 18px 42px rgba(41, 51, 45, .16), 0 3px 10px rgba(41, 51, 45, .08)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#276e4f",
      'subject-chemistry-bg': "#dfeee7",
      'subject-maths': "#a03d78",
      'subject-maths-bg': "#f6e2ec",
      'subject-physics': "#0e6d8c",
      'subject-physics-bg': "#dceef4",
      'surface-cool': "#e6eff5",
      'surface-cool-accent': "#1b627f",
      'surface-cool-accent-bg': "#d8e7ee",
      'surface-cool-border': "#a4c1d2",
      'surface-cool-ink': "#13475f",
      'surface-cool-muted': "#2a526c",
      'surface-tip': "#f1e7f0",
      'surface-tip-accent': "#7f3e6d",
      'surface-tip-accent-bg': "#e9d6e4",
      'surface-tip-border': "#c6aac6",
      'surface-tip-ink': "#562b4e",
      'surface-tip-muted': "#613f64",
      'surface-warm': "#f5ede5",
      'surface-warm-border': "#d3c1ae",
      'surface-warm-ink': "#694f32",
      'surface-warm-line': "#bdb1a7",
      'surface-warm-muted': "#6b5a4d",
      'surface-warm-strong': "#7e5c34",
      'text-accent': "#0b5a76",
      'text-muted': "#4e566c",
      'text-primary': "#171c2b",
      'tint-cool': "#0f6f8f",
      'tint-green-border': "#a4bebc",
      'tint-green-ink': "#285c4c",
      'tint-green-surface': "#ebf2f2",
      'tint-tip': "#a03d78",
      'tint-warm': "#c98a3a",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#f0efd4",
    },
  },
  dark: {
    'default': {
      'accent': "#a9bfdc",
      'accent-dark': "#9db4d3",
      'accent-light': "#384556",
      'bg': "#202522",
      'blue-bg': "#354352",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#526d9c",
      'button-primary-border': "#475f8b",
      'button-primary-hover': "#465f8e",
      'button-primary-ink': "#ffffff",
      'button-primary-shadow': "#3e5379",
      'chart-grid': "#4d584f",
      'fab-bg': "#a9bfdc",
      'fab-border': "#9db4d3",
      'fab-ink': "#ffffff",
      'focus-accent': "#e1c577",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#a6d9aa",
      'green-bg': "#344737",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#ecede4",
      'ink-soft': "#c2c9bc",
      'line': "#3c453e",
      'line-strong': "#566055",
      'muted': "#a0a89d",
      'orange': "#efbd7d",
      'orange-bg': "#4c3e2e",
      'paper': "#2b312d",
      'paper-muted': "#252b27",
      'paper-soft': "#303733",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f39c94",
      'red-bg': "#4a3431",
      'ring-track': "#4c574e",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4c3e2e",
      'score-okay-fg': "#f3ce9f",
      'score-strong-bg': "#344737",
      'score-strong-fg': "#bde3c0",
      'score-weak-bg': "#4a3431",
      'score-weak-fg': "#f6b6b0",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#90d2a1",
      'subject-chemistry-bg': "#354b3d",
      'subject-maths': "#f0b174",
      'subject-maths-bg': "#594532",
      'subject-physics': "#93b7ef",
      'subject-physics-bg': "#37485d",
      'surface-cool': "#2f3739",
      'surface-cool-accent': "#718fb4",
      'surface-cool-accent-bg': "#313c41",
      'surface-cool-border': "#42525c",
      'surface-cool-ink': "#9cb0c9",
      'surface-cool-muted': "#97aab8",
      'surface-tip': "#3a3c30",
      'surface-tip-accent': "#b8a46e",
      'surface-tip-accent-bg': "#464433",
      'surface-tip-border': "#625e42",
      'surface-tip-ink': "#d2c39d",
      'surface-tip-muted': "#bcb491",
      'surface-warm': "#3f3f30",
      'surface-warm-border': "#6a6241",
      'surface-warm-ink': "#dac79b",
      'surface-warm-line': "#777151",
      'surface-warm-muted': "#c3b994",
      'surface-warm-strong': "#d5bd88",
      'text-accent': "#c2d2e7",
      'text-muted': "#bdc5ba",
      'text-primary': "#ecede4",
      'tint-cool': "#5278b1",
      'tint-green-border': "#5a6e5c",
      'tint-green-ink': "#b1d3b1",
      'tint-green-surface': "#343d36",
      'tint-tip': "#b3924a",
      'tint-warm': "#c49a46",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#514a32",
    },
    'sunset-blaze': {
      'accent': "#f0a273",
      'accent-dark': "#f2ae83",
      'accent-light': "#4b2e21",
      'bg': "#251b17",
      'blue-bg': "#43303c",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#f0a273",
      'button-primary-border': "#906145",
      'button-primary-hover': "#f3b38c",
      'button-primary-ink': "#251b17",
      'button-primary-shadow': "#78513a",
      'chart-grid': "#4e3c34",
      'fab-bg': "#f0a273",
      'fab-border': "#f2ae83",
      'fab-ink': "#ffffff",
      'focus-accent': "#e0955a",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#abd3a0",
      'green-bg': "#33422c",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#f4eae2",
      'ink-soft': "#d9c7bc",
      'line': "#473731",
      'line-strong': "#614b42",
      'muted': "#b49d92",
      'orange': "#efb57a",
      'orange-bg': "#4d3a24",
      'paper': "#302420",
      'paper-muted': "#2a1f1a",
      'paper-soft': "#362a25",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f2a098",
      'red-bg': "#4d2f2a",
      'ring-track': "#4c3a31",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4d3a24",
      'score-okay-fg': "#f3c89d",
      'score-strong-bg': "#33422c",
      'score-strong-fg': "#c1deb9",
      'score-weak-bg': "#4d2f2a",
      'score-weak-fg': "#f5b9b3",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#cbd07f",
      'subject-chemistry-bg': "#3d3d24",
      'subject-maths': "#f2ae67",
      'subject-maths-bg': "#4d3521",
      'subject-physics': "#e795ac",
      'subject-physics-bg': "#4b2b36",
      'surface-cool': "#402e2d",
      'surface-cool-accent': "#e3a3b0",
      'surface-cool-accent-bg': "#4b3535",
      'surface-cool-border': "#714f51",
      'surface-cool-ink': "#edbec6",
      'surface-cool-muted': "#deb4b6",
      'surface-tip': "#443428",
      'surface-tip-accent': "#e0ba84",
      'surface-tip-accent-bg': "#54412f",
      'surface-tip-border': "#795f43",
      'surface-tip-ink': "#ecd1ab",
      'surface-tip-muted': "#ddc09d",
      'surface-warm': "#473128",
      'surface-warm-border': "#7b5340",
      'surface-warm-ink': "#ebbea4",
      'surface-warm-line': "#875e4a",
      'surface-warm-muted': "#dbb29b",
      'surface-warm-strong': "#e8b294",
      'text-accent': "#f2ae83",
      'text-muted': "#c4ada1",
      'text-primary': "#f4eae2",
      'tint-cool': "#e795ac",
      'tint-green-border': "#636350",
      'tint-green-ink': "#bcceab",
      'tint-green-surface': "#393029",
      'tint-tip': "#e3b46a",
      'tint-warm': "#e08a5c",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#4d432a",
    },
    'forest-emerald': {
      'accent': "#7fc49f",
      'accent-dark': "#90cfae",
      'accent-light': "#2a4234",
      'bg': "#161f19",
      'blue-bg': "#2c3d50",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#7fc49f",
      'button-primary-border': "#4c765f",
      'button-primary-hover': "#96cfb0",
      'button-primary-ink': "#161f19",
      'button-primary-shadow': "#406250",
      'chart-grid': "#405045",
      'fab-bg': "#7fc49f",
      'fab-border': "#90cfae",
      'fab-ink': "#ffffff",
      'focus-accent': "#b7d18c",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#a5d8ac",
      'green-bg': "#2f4530",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#e9efe6",
      'ink-soft': "#c2cec0",
      'line': "#34423a",
      'line-strong': "#4c5f52",
      'muted': "#9db1a0",
      'orange': "#e8b478",
      'orange-bg': "#4a3a24",
      'paper': "#212b24",
      'paper-muted': "#1c251e",
      'paper-soft': "#263128",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f0a098",
      'red-bg': "#48302c",
      'ring-track': "#3e4e43",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4a3a24",
      'score-okay-fg': "#eec89b",
      'score-strong-bg': "#2f4530",
      'score-strong-fg': "#bce2c2",
      'score-weak-bg': "#48302c",
      'score-weak-fg': "#f4b9b3",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#8fd0ab",
      'subject-chemistry-bg': "#2b4536",
      'subject-maths': "#e8b478",
      'subject-maths-bg': "#4a3a24",
      'subject-physics': "#8fb7e0",
      'subject-physics-bg': "#2c3d50",
      'surface-cool': "#29392f",
      'surface-cool-accent': "#92c7a8",
      'surface-cool-accent-bg': "#2f4236",
      'surface-cool-border': "#486454",
      'surface-cool-ink': "#b2d9c1",
      'surface-cool-muted': "#a9cab3",
      'surface-tip': "#333d2e",
      'surface-tip-accent': "#c7cf94",
      'surface-tip-accent-bg': "#434c36",
      'surface-tip-border': "#646f50",
      'surface-tip-ink': "#dae0b7",
      'surface-tip-muted': "#c5cea7",
      'surface-warm': "#393c2f",
      'surface-warm-border': "#6c674f",
      'surface-warm-ink': "#e1d2b3",
      'surface-warm-line': "#76775d",
      'surface-warm-muted': "#c9c4a8",
      'surface-warm-strong': "#dfcaa6",
      'text-accent': "#a5d8bc",
      'text-muted': "#b0c1b2",
      'text-primary': "#e9efe6",
      'tint-cool': "#7fc49f",
      'tint-green-border': "#546c5a",
      'tint-green-ink': "#b0d4b4",
      'tint-green-surface': "#2a372e",
      'tint-tip': "#c9cf7f",
      'tint-warm': "#d8b078",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#45442c",
    },
    'sandalwood': {
      'accent': "#d3a877",
      'accent-dark': "#dcb587",
      'accent-light': "#453823",
      'bg': "#201a13",
      'blue-bg': "#33404d",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#d3a877",
      'button-primary-border': "#7f6547",
      'button-primary-hover': "#dbb88f",
      'button-primary-ink': "#201a13",
      'button-primary-shadow': "#6a543c",
      'chart-grid': "#4c4232",
      'fab-bg': "#d3a877",
      'fab-border': "#dcb587",
      'fab-ink': "#ffffff",
      'focus-accent': "#c9a35f",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#a9d3a0",
      'green-bg': "#32452d",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#f0e8da",
      'ink-soft': "#d3c7b2",
      'line': "#443a2b",
      'line-strong': "#5d5140",
      'muted': "#ad9e86",
      'orange': "#e8b478",
      'orange-bg': "#4a3a24",
      'paper': "#2b241b",
      'paper-muted': "#251f17",
      'paper-soft': "#312a20",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f0a098",
      'red-bg': "#4a302b",
      'ring-track': "#4a4030",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4a3a24",
      'score-okay-fg': "#eec89b",
      'score-strong-bg': "#32452d",
      'score-strong-fg': "#bfdeb9",
      'score-weak-bg': "#4a302b",
      'score-weak-fg': "#f4b9b3",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#b3cf96",
      'subject-chemistry-bg': "#39452c",
      'subject-maths': "#e8b478",
      'subject-maths-bg': "#4a3a24",
      'subject-physics': "#9fb7d0",
      'subject-physics-bg': "#33404d",
      'surface-cool': "#35312a",
      'surface-cool-accent': "#aebbbf",
      'surface-cool-accent-bg': "#3c3a34",
      'surface-cool-border': "#5c5b53",
      'surface-cool-ink': "#c6cfcf",
      'surface-cool-muted': "#bfc1b9",
      'surface-tip': "#3d3525",
      'surface-tip-accent': "#cec08c",
      'surface-tip-accent-bg': "#4b432e",
      'surface-tip-border': "#6f6444",
      'surface-tip-ink': "#dfd4ae",
      'surface-tip-muted': "#d0c39d",
      'surface-warm': "#413527",
      'surface-warm-border': "#755f45",
      'surface-warm-ink': "#e3cbac",
      'surface-warm-line': "#806b51",
      'surface-warm-muted': "#d3bc9e",
      'surface-warm-strong': "#dfc3a1",
      'text-accent': "#dcb587",
      'text-muted': "#bcae95",
      'text-primary': "#f0e8da",
      'tint-cool': "#9fb7c4",
      'tint-green-border': "#60654c",
      'tint-green-ink': "#b9cea7",
      'tint-green-surface': "#343024",
      'tint-tip': "#cbbd7a",
      'tint-warm': "#d3a877",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#47422a",
    },
    'ocean-deep': {
      'accent': "#7db6dd",
      'accent-dark': "#92c3e4",
      'accent-light': "#23405a",
      'bg': "#0f1a24",
      'blue-bg': "#263c52",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#7db6dd",
      'button-primary-border': "#4b6d85",
      'button-primary-hover': "#94c3e3",
      'button-primary-ink': "#0f1a24",
      'button-primary-shadow': "#3f5b6f",
      'chart-grid': "#35485a",
      'fab-bg': "#7db6dd",
      'fab-border': "#92c3e4",
      'fab-ink': "#ffffff",
      'focus-accent': "#6fb5c9",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#93d3b4",
      'green-bg': "#24443a",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#e4edf3",
      'ink-soft': "#bccdd9",
      'line': "#2a3d4c",
      'line-strong': "#3f586b",
      'muted': "#92a7b4",
      'orange': "#e8b478",
      'orange-bg': "#4a3a24",
      'paper': "#192733",
      'paper-muted': "#15212b",
      'paper-soft': "#1e2e3c",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f0a098",
      'red-bg': "#46302f",
      'ring-track': "#33465a",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4a3a24",
      'score-okay-fg': "#eec89b",
      'score-strong-bg': "#24443a",
      'score-strong-fg': "#afdec8",
      'score-weak-bg': "#46302f",
      'score-weak-fg': "#f4b9b3",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#6fd0c0",
      'subject-chemistry-bg': "#1f4440",
      'subject-maths': "#e8b478",
      'subject-maths-bg': "#4a3a24",
      'subject-physics': "#8fb7e0",
      'subject-physics-bg': "#263c52",
      'surface-cool': "#223442",
      'surface-cool-accent': "#8fbcdc",
      'surface-cool-accent-bg': "#283c4d",
      'surface-cool-border': "#405c72",
      'surface-cool-ink': "#aed0e8",
      'surface-cool-muted': "#a4c4db",
      'surface-tip': "#223a43",
      'surface-tip-accent': "#88cfc8",
      'surface-tip-accent-bg': "#2a494f",
      'surface-tip-border': "#406c71",
      'surface-tip-ink': "#aee0dc",
      'surface-tip-muted': "#9fced0",
      'surface-warm': "#34393c",
      'surface-warm-border': "#6b655b",
      'surface-warm-ink': "#e6d3ba",
      'surface-warm-line': "#72746f",
      'surface-warm-muted': "#cbc5b8",
      'surface-warm-strong': "#e6ccac",
      'text-accent': "#a5d0ea",
      'text-muted': "#a5b8c4",
      'text-primary': "#e4edf3",
      'tint-cool': "#7db6dd",
      'tint-green-border': "#476769",
      'tint-green-ink': "#a3d1c2",
      'tint-green-surface': "#22333c",
      'tint-tip': "#6fd0c0",
      'tint-warm': "#e8b478",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#43422a",
    },
    'sakura-blossom': {
      'accent': "#e39ab8",
      'accent-dark': "#eaaac4",
      'accent-light': "#4a2b3a",
      'bg': "#241920",
      'blue-bg': "#402b48",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#e39ab8",
      'button-primary-border': "#885c6e",
      'button-primary-hover': "#e8acc5",
      'button-primary-ink': "#241920",
      'button-primary-shadow': "#724d5c",
      'chart-grid': "#4c3a45",
      'fab-bg': "#e39ab8",
      'fab-border': "#eaaac4",
      'fab-ink': "#ffffff",
      'focus-accent': "#d98aa6",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#a9d3a0",
      'green-bg': "#32452d",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#f3e7ec",
      'ink-soft': "#d6c1cb",
      'line': "#46343f",
      'line-strong': "#604a57",
      'muted': "#b099a6",
      'orange': "#eab183",
      'orange-bg': "#4a3524",
      'paper': "#302229",
      'paper-muted': "#291d23",
      'paper-soft': "#36272f",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f2a0ac",
      'red-bg': "#4a2b31",
      'ring-track': "#4a3843",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4a3524",
      'score-okay-fg': "#efc5a3",
      'score-strong-bg': "#32452d",
      'score-strong-fg': "#bfdeb9",
      'score-weak-bg': "#4a2b31",
      'score-weak-fg': "#f5b9c2",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#b3cf9d",
      'subject-chemistry-bg': "#37422a",
      'subject-maths': "#eab183",
      'subject-maths-bg': "#4a3524",
      'subject-physics': "#cfa3dd",
      'subject-physics-bg': "#402b48",
      'surface-cool': "#3e2e39",
      'surface-cool-accent': "#d1abd8",
      'surface-cool-accent-bg': "#483544",
      'surface-cool-border': "#6a5168",
      'surface-cool-ink': "#e0c4e4",
      'surface-cool-muted': "#d3b6d2",
      'surface-tip': "#442f39",
      'surface-tip-accent': "#dfa6be",
      'surface-tip-accent-bg': "#543a46",
      'surface-tip-border': "#785566",
      'surface-tip-ink': "#ecc4d4",
      'surface-tip-muted': "#dbb2c4",
      'surface-warm': "#47323c",
      'surface-warm-border': "#7b5768",
      'surface-warm-ink': "#ecc4d4",
      'surface-warm-line': "#876274",
      'surface-warm-muted': "#dab4c5",
      'surface-warm-strong': "#eabace",
      'text-accent': "#eec0d4",
      'text-muted': "#c2abb7",
      'text-primary': "#f3e7ec",
      'tint-cool': "#cfa3dd",
      'tint-green-border': "#62615a",
      'tint-green-ink': "#baccb0",
      'tint-green-surface': "#382e31",
      'tint-tip': "#e39ab8",
      'tint-warm': "#e39ab8",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#4a4130",
    },
    'dracula-midnight': {
      'accent': "#bd93f9",
      'accent-dark': "#cab0ff",
      'accent-light': "#3d3458",
      'bg': "#282a36",
      'blue-bg': "#383a5e",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#bd93f9",
      'button-primary-border': "#715895",
      'button-primary-hover': "#c9a6fa",
      'button-primary-ink': "#282a36",
      'button-primary-shadow': "#5f4a7d",
      'chart-grid': "#4a4d62",
      'fab-bg': "#bd93f9",
      'fab-border': "#cab0ff",
      'fab-ink': "#ffffff",
      'focus-accent': "#bd93f9",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#69f794",
      'green-bg': "#2b4a38",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#f8f8f2",
      'ink-soft': "#dcdcd2",
      'line': "#44475a",
      'line-strong': "#6272a4",
      'muted': "#a0a2b4",
      'orange': "#ffb86c",
      'orange-bg': "#4d3d28",
      'paper': "#343746",
      'paper-muted': "#2e3040",
      'paper-soft': "#3a3d4d",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#ff6e6e",
      'red-bg': "#4d2b30",
      'ring-track': "#484b60",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4d3d28",
      'score-okay-fg': "#ffca92",
      'score-strong-bg': "#2b4a38",
      'score-strong-fg': "#90f9b0",
      'score-weak-bg': "#4d2b30",
      'score-weak-fg': "#ff9494",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#50fa7b",
      'subject-chemistry-bg': "#2b4a38",
      'subject-maths': "#ffb86c",
      'subject-maths-bg': "#4d3d28",
      'subject-physics': "#8be9fd",
      'subject-physics-bg': "#2b3d50",
      'surface-cool': "#3c4756",
      'surface-cool-accent': "#a2e5f1",
      'surface-cool-accent-bg': "#415261",
      'surface-cool-border': "#567184",
      'surface-cool-ink': "#bff0f8",
      'surface-cool-muted': "#bde1e2",
      'surface-tip': "#43415a",
      'surface-tip-accent': "#c7aaed",
      'surface-tip-accent-bg': "#4f496a",
      'surface-tip-border': "#6b5f8d",
      'surface-tip-ink': "#ddcaf5",
      'surface-tip-muted': "#d0c0e1",
      'surface-warm': "#4e484b",
      'surface-warm-border': "#846d60",
      'surface-warm-ink': "#fbdbb4",
      'surface-warm-line': "#918793",
      'surface-warm-muted': "#e8d0af",
      'surface-warm-strong': "#fcd3a4",
      'text-accent': "#cab0ff",
      'text-muted': "#b3b5c6",
      'text-primary': "#f8f8f2",
      'tint-cool': "#8be9fd",
      'tint-green-border': "#4e786a",
      'tint-green-ink': "#95edac",
      'tint-green-surface': "#38444b",
      'tint-tip': "#bd93f9",
      'tint-warm': "#ffb86c",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#4a4634",
    },
    'lavender-mist': {
      'accent': "#b1a3e8",
      'accent-dark': "#bfb2ef",
      'accent-light': "#37315a",
      'bg': "#1b1926",
      'blue-bg': "#303455",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#b1a3e8",
      'button-primary-border': "#6a628b",
      'button-primary-hover': "#bfb4ec",
      'button-primary-ink': "#1b1926",
      'button-primary-shadow': "#595274",
      'chart-grid': "#413e58",
      'fab-bg': "#b1a3e8",
      'fab-border': "#bfb2ef",
      'fab-ink': "#ffffff",
      'focus-accent': "#a596d9",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#a5d8ac",
      'green-bg': "#2f4531",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#eceaf5",
      'ink-soft': "#cbc8db",
      'line': "#3a3750",
      'line-strong': "#514d6e",
      'muted': "#a5a2b9",
      'orange': "#e8b478",
      'orange-bg': "#4a3a24",
      'paper': "#262434",
      'paper-muted': "#211f2d",
      'paper-soft': "#2c293b",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#f0a0ac",
      'red-bg': "#482c34",
      'ring-track': "#3f3c56",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#4a3a24",
      'score-okay-fg': "#eec89b",
      'score-strong-bg': "#2f4531",
      'score-strong-fg': "#bce2c2",
      'score-weak-bg': "#482c34",
      'score-weak-fg': "#f4b9c2",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#9fd0ae",
      'subject-chemistry-bg': "#2c4437",
      'subject-maths': "#e8b478",
      'subject-maths-bg': "#4a3a24",
      'subject-physics': "#a3b1f0",
      'subject-physics-bg': "#303455",
      'surface-cool': "#313145",
      'surface-cool-accent': "#aeb7ea",
      'surface-cool-accent-bg': "#393950",
      'surface-cool-border': "#55577a",
      'surface-cool-ink': "#c6ccf2",
      'surface-cool-muted': "#bcbfe3",
      'surface-tip': "#353248",
      'surface-tip-accent': "#b9afe4",
      'surface-tip-accent-bg': "#423d58",
      'surface-tip-border': "#605a81",
      'surface-tip-ink': "#d1c9ef",
      'surface-tip-muted': "#c1bae0",
      'surface-warm': "#38354b",
      'surface-warm-border': "#625c84",
      'surface-warm-ink': "#d1c9ef",
      'surface-warm-line': "#6e6793",
      'surface-warm-muted': "#c2bbdf",
      'surface-warm-strong': "#cac1ed",
      'text-accent': "#cfc4f5",
      'text-muted': "#b7b4c9",
      'text-primary': "#eceaf5",
      'tint-cool': "#a3b1f0",
      'tint-green-border': "#58646a",
      'tint-green-ink': "#b3d2be",
      'tint-green-surface': "#2f313c",
      'tint-tip': "#b1a3e8",
      'tint-warm': "#b1a3e8",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#454130",
    },
    'cyberpunk-neon': {
      'accent': "#45d8f0",
      'accent-dark': "#6ae2f5",
      'accent-light': "#10333f",
      'bg': "#0d0f1a",
      'blue-bg': "#113340",
      'body-scale': "1",
      'button-danger-bg': "#a84840",
      'button-danger-border': "#8f3a33",
      'button-danger-hover': "#9c4038",
      'button-danger-ink': "#ffffff",
      'button-danger-shadow': "#7c332c",
      'button-primary-bg': "#45d8f0",
      'button-primary-border': "#298290",
      'button-primary-hover': "#66dff3",
      'button-primary-ink': "#0d0f1a",
      'button-primary-shadow': "#236c78",
      'chart-grid': "#2c3350",
      'fab-bg': "#45d8f0",
      'fab-border': "#6ae2f5",
      'fab-ink': "#ffffff",
      'focus-accent': "#22d3ee",
      'focus-bg-a': "#303f33",
      'focus-bg-b': "#222c26",
      'focus-bg-c': "#1a211e",
      'focus-caption': "#bccaa6",
      'focus-control-bg': "#303a30",
      'focus-control-border': "#4a574a",
      'focus-control-ink': "#e2e7d8",
      'focus-control-muted': "#9aa696",
      'focus-faint': "#93a28c",
      'focus-ink': "#edf0e6",
      'focus-line': "#465548",
      'focus-muted': "#a8b2a3",
      'focus-orbit': "#55654f",
      'focus-panel': "#2a352d",
      'focus-panel-line': "#3f4e42",
      'focus-selected-bg': "rgba(195, 199, 149, 0.24)",
      'focus-selected-border': "#93a06c",
      'focus-selected-ink': "#eef0dc",
      'focus-soft': "#c9d3c2",
      'focus-star': "#d4bb71",
      'font-body': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-default-reading': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'font-heading': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-identity': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-label': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-number': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-public': "'Patrick Hand', 'Segoe Print', 'Bradley Hand', cursive",
      'font-ui': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'green': "#4ade80",
      'green-bg': "#123527",
      'heat-border': "rgba(220, 226, 213, 0.14)",
      'heat-goal': "#b3924a",
      'heat-high': "#6f9a74",
      'heat-low': "#3c4a3c",
      'heat-medium': "#4f6a52",
      'heat-none': "#2c332d",
      'ink': "#e8ecf8",
      'ink-soft': "#c3cadf",
      'line': "#262c42",
      'line-strong': "#3a4263",
      'muted': "#97a0bd",
      'orange': "#fbbf24",
      'orange-bg': "#3a3013",
      'paper': "#161a2a",
      'paper-muted': "#121522",
      'paper-soft': "#1a1f31",
      'radius': "16px",
      'reading-font-family': "'Lexend', 'Trebuchet MS', system-ui, sans-serif",
      'red': "#ff6b6b",
      'red-bg': "#3d1a1e",
      'ring-track': "#2a314e",
      'safe-bottom': "env(safe-area-inset-bottom, 0px)",
      'score-okay-bg': "#3a3013",
      'score-okay-fg': "#fcd05d",
      'score-strong-bg': "#123527",
      'score-strong-fg': "#79e7a1",
      'score-weak-bg': "#3d1a1e",
      'score-weak-fg': "#ff9191",
      'shadow': "0 11px 27px rgba(0, 0, 0, .17), 0 2px 7px rgba(0, 0, 0, .13)",
      'shadow-float': "0 20px 50px rgba(0, 0, 0, .45), 0 4px 12px rgba(0, 0, 0, .2)",
      'shell-x': "clamp(14px, 3.4vw, 78px)",
      'sidebar-w': "clamp(214px, 8.5vw + 130px, 272px)",
      'sidebar-x': "clamp(9px, .9vw + 4px, 15px)",
      'subject-chemistry': "#34d399",
      'subject-chemistry-bg': "#0f3a2c",
      'subject-maths': "#ff5ea8",
      'subject-maths-bg': "#3d1430",
      'subject-physics': "#45d8f0",
      'subject-physics-bg': "#113340",
      'surface-cool': "#1a2b3c",
      'surface-cool-accent': "#68d4eb",
      'surface-cool-accent-bg': "#1d3748",
      'surface-cool-border': "#2e596f",
      'surface-cool-ink': "#93e2f4",
      'surface-cool-muted': "#93cfe5",
      'surface-tip': "#302138",
      'surface-tip-accent': "#ec81ba",
      'surface-tip-accent-bg': "#452843",
      'surface-tip-border': "#6b3c63",
      'surface-tip-ink': "#f3abd3",
      'surface-tip-muted': "#daa1ca",
      'surface-warm': "#342f29",
      'surface-warm-border': "#6e5e38",
      'surface-warm-ink': "#f1d796",
      'surface-warm-line': "#746850",
      'surface-warm-muted': "#d6c69f",
      'surface-warm-strong': "#f3d27d",
      'text-accent': "#7deaff",
      'text-muted': "#aab3cd",
      'text-primary': "#e8ecf8",
      'tint-cool': "#45d8f0",
      'tint-green-border': "#305e53",
      'tint-green-ink': "#78d6a4",
      'tint-green-surface': "#1a2830",
      'tint-tip': "#ff5ea8",
      'tint-warm': "#fbbf24",
      'type-alert-size': ".9375rem",
      'type-badge-size': ".75rem",
      'type-body-size': "1rem",
      'type-brand-size': "1.75rem",
      'type-button-size': ".9375rem",
      'type-caption-size': ".875rem",
      'type-display-size': "2.25rem",
      'type-empty-size': "1.25rem",
      'type-h1-size': "2rem",
      'type-h2-size': "1.5rem",
      'type-h3-size': "1.25rem",
      'type-input-size': "1rem",
      'type-metric-size': "2rem",
      'type-nav-size': ".9375rem",
      'type-overline-size': ".75rem",
      'type-table-size': ".9375rem",
      'yellow-bg': "#3a3413",
    },
  },
} as const
